name: Sign Request
description: File a Sign Request for a plugin
assignees: codecat

body:
- type: input
  id: Name
  attributes:
    label: Name
    description: The Name of your plugin.
    placeholder: 'ex: JAMP (Just Another Medals Plugin)'
  validations:
    required: true

- type: textarea
  id: Description
  attributes:
    label: Description
    description: The Description of your plugin.
    placeholder: |
      Another Medals Plugin, because we didn't have enough of them already!
    #[![Kappa](https://cdn.frankerfacez.com/emote/480788/1)](https://openplanet.nl/files?search=Medal)
  validations:
    required: false

- type: dropdown
  id: Signed
  attributes:
    label: Has This Plugin been signed before?
    description: Have you successfuly submitted this plugin for signing?
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true

- type: dropdown
  id: Forced-Perms
  attributes:
    label: Did you add minimum required permisions?
    description: Did you provide a `perms` meta value or a `#perms` preprocessor option?
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true

- type: dropdown
  id: Dynamic-Perms
  attributes:
    label: Did you use `Permissions.as`?
    description: Did you dynamically detemine whether the user has permissions for something using `Permissions.as`?
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true

- type: textarea
  id: plugin
  attributes:
    label: Your Plugin
    description: Attach your plugin here.
    placeholder: "Drag 'n Drop your plugin here"
  validations:
    required: true
