name: Sign Request
description: File Sign Request
title: '[SIGN🔐] <Plugin-Name> <Plugin-version>'
#assignees: codecat

body:
- type: input
  id: Name
  attributes:
    label: Name
    description: The Name of your plugin.
    placeholder: 'ex: JAMP (Just Another Medals Plugin)'
  validations:
    required: true

- type: textarea
  id: Description
  attributes:
    label: Description
    description: The Description of your plugin.
  validations:
    required: false

- type: dropdown
  id: Signed
  attributes:
    label: Has This Plugin beed signed before?
    description: Have you successfuly submited this plugin for signing?
    options:
      - 'Yes'
      - 'No'
    validation:
      required: true

- type: dropdown
  id: Forced-Perms
  attributes:
    label: Did you Add minimum required permisions?
    description: Did you provide a `perms` meta value or a `#perms` preprocessor option?
    options:
      - 'Yes'
      - 'No'
    validation:
      required: true

- type: dropdown
  id: Dynamic-Perms
  attributes:
    label: Did you use `Permissions.as`?
    description: Did you dynamicaly detemine whether the user has permisions for somethin using `Permissions.as`?
    options:
      - 'Yes'
      - 'No'
    validation:
      required: true

- type: textarea
  id: plugin
  attributes:
    label: Your Plugin
    description: Attach your plugin here.
    placehoder: "Drag 'n Drop your plugin here"
  validations:
    required: true
